install.packages('remotes')

remotes::install_version("checkmate", version = "2.0.0", upgrade = FALSE)
remotes::install_version("here", version = "0.1", upgrade = FALSE)
remotes::install_version("dplyr", version = "1.0.7", upgrade = FALSE)
remotes::install_version("tidyr", version = "1.1.4", upgrade = FALSE)
remotes::install_version("ggplot2", version = "3.3.5", upgrade = FALSE)
remotes::install_version("gridExtra", version = "2.3", upgrade = FALSE)
remotes::install_version("ggsci", version = "2.9", upgrade = FALSE)
remotes::install_version("ggridges", version = "0.5.3", upgrade = FALSE)
remotes::install_version("knitr", version = "1.36", upgrade = FALSE)
remotes::install_version("pROC", version = "1.18.0", upgrade = FALSE)
remotes::install_version("batchtools", version = "0.9.15", upgrade = FALSE)
remotes::install_version("sysfonts", version = "0.8.1", upgrade = FALSE)
remotes::install_version("extrafont", version = "0.17", upgrade = FALSE)
remotes::install_version("ggridges", version = "0.5.3", upgrade = FALSE)
remotes::install_version("ggsci", version = "2.9", upgrade = FALSE)
remotes::install_version("latex2exp", version = "0.5.0", upgrade = FALSE)
remotes::install_version("jsonlite", version = "1.7.3", upgrade = FALSE)
remotes::install_version("nloptr", version = "1.2.2.3", upgrade = FALSE)
remotes::install_version("ggpubr", version = "0.3.0", upgrade = FALSE)
remotes::install_version("rmarkdown", version = "2.11", upgrade = FALSE)
remotes::install_version("data.table", version = "1.14.8", upgrade = FALSE)
